"""empty message

Revision ID: 20a2caec38cc
Revises: 581b988b8feb
Create Date: 2023-04-27 07:12:22.139758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a2caec38cc'
down_revision = '581b988b8feb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TradingItem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imgurl', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TradingItem', schema=None) as batch_op:
        batch_op.drop_column('imgurl')

    # ### end Alembic commands ###
