"""empty message

Revision ID: 581b988b8feb
Revises: 886e5d52fe2d
Create Date: 2023-04-27 06:41:32.030818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581b988b8feb'
down_revision = '886e5d52fe2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TradingItem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('TradingItem_type_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'TradingType', ['type_id'], ['id'])
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TradingItem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('TradingItem_type_fkey', 'TradingType', ['type'], ['id'])
        batch_op.drop_column('type_id')

    # ### end Alembic commands ###
