"""empty message

Revision ID: b501272dfa5a
Revises: 20a2caec38cc
Create Date: 2023-04-27 08:25:37.147964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b501272dfa5a'
down_revision = '20a2caec38cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tradingtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tradingitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('imgurl', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['tradingtype.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('TradingItem')
    op.drop_table('TradingType')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TradingType',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"TradingType_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='TradingType_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('TradingItem',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"TradingItem_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('imgurl', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['TradingType.id'], name='TradingItem_type_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='TradingItem_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='TradingItem_pkey')
    )
    op.drop_table('tradingitem')
    op.drop_table('tradingtype')
    # ### end Alembic commands ###
